---
title: "The Unforeseen Negative Impacts of Cristiano Ronaldo on His Teammates: An Analysis of The So Far Pedestrian Manchester United 2021-2022 Campaign"
author: "John Michael Tarricone"
date: "1/19/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.0 Introduction

Manchester United is a storied football club rich in historical success in the Premier League era. It is routinely valued as one the most expensive sports organizations in the world (The New York Times, 2012). Under the management of legendary Sir Alex Fergason from 1986-2012, the club won 13 Priemer League (PL) titles, two UEFA champions (UCL), and were a consistent force on top of world football.
  
In the 8 seasons since Sir Alex's departure, the club trajectory has taken a significant downturn. During this period they have gone through seven different managers, are yet to win a PL title, and haven't advanced past the quarter final in UCL. This is not despite serious investment for ownership - during this period the Glazer family and management organization has spent XXXX, "second" only to it's neighbors Manchester City.
  
The club finished second in 2020-2021 PL campaign and hopes were high for 2021-2022 season. These expectations were enhanced with the resigning of club legend Cristiano Ronaldo (CR) on August 31, 2021. CR is known at one of the greatest footballers ever, 


